// Generated by CoffeeScript 1.3.3

window.onload =
(function() {
  var name, _i, _len, _ref;

  _ref = ["藤原", "高橋", "須藤"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    name = _ref[_i];
    alert("こんにちわ" + name + "さん");
  }

}).call(this);
